### ISSUE TITLE
GREAT ERROR! ???

### ISSUE THREAD

**Issue by Blueeyestar** [Puyodead1-Development/SpigotServerBuilder#1]
I love this plugin, simply invaluable and above all simple. It does what it should and does it clean and fast... At the end there is always an error error what does it have on it?

Set output path to: spigot
Started!
Windows Detected
Directory Exists!
Created Directory at: spigot\SpigotServer
Created Directory at: spigot\BuildTools
Checking for BuildTools.jar in BuildTools Directory...
BuildTools.jar not found, Checking for Spigot
We didn't find Spigot :(
Downloaded BuildTools.jar!
Waiting...
Done...
GREAT ERROR!

**Comment by Puyodead1** [comment]
Oh Boy, I will take a look, thanks for letting me know!

**Comment by Puyodead1** [comment]
That error is because it cannot find BuildTools in the directory. Are there any spaces in the path?

**Comment by Blueeyestar** [comment]
no the file is on the desktop and is called Spigot.
I simply write in the path Spigot and he makes it correctly there. ES works except the error message that always comes up

**Comment by Puyodead1** [comment]
Ok I will try and fix it

**Comment by Puyodead1** [comment]
Are you selecting a specific version?

**Comment by Blueeyestar** [comment]
I always take the latest version.

**Comment by Puyodead1** [comment]
Okay

**Comment by Puyodead1** [comment]
I am unable to find what is causing it. But i will release a new version soon with some better error catching.

**Comment by Puyodead1** [comment]
Gonna close this issues finally, I have updated this resource also.
