### ISSUE TITLE
Cant Pull From Git

### ISSUE THREAD

**Issue by Swipperr** [Puyodead1-Development/SpigotServerBuilder#2]
"Starting...
Using version: 1.14-pre5
Windows Detected
Loading BuildTools version: git-BuildTools-19d26b6-120 (#120)
Java Version: Java 8
Current Path: C:\Users\seths\Downloads\kilakme\BuildTools\.
Could not successfully run git. Please ensure it is installed and functioning. Cannot run program "git" (in directory "."): CreateProcess error=2, The system cannot find the file specified" Im not sure what to say because I doubt anyone looks at the issues tab but uh, there's nothing in the "spigot" folder it made and there's only this in the other one
![image](https://user-images.githubusercontent.com/67619343/90377671-5238ad00-e046-11ea-88b4-9638e648d8c8.png)

**Comment by Puyodead1** [comment]
Hey there! Sorry you’re having issues, would you mind posting the buildtools.log.txt file so I can investigate? Thanks!

**Comment by Swipperr** [comment]
puyo i can assure you that the log says the exact same thing just without the "windows detected" line

But, because you asked i guess i have 2 
[BuildTools.log.txt](https://github.com/Puyodead1-Development/SpigotServerBuilder/files/5087643/BuildTools.log.txt)

**Comment by Puyodead1** [comment]
ah, i didnt know it was the same. mb

**Comment by Puyodead1** [comment]
Which version are you using?

**Comment by Swipperr** [comment]
the latest, 2.5.

**Comment by Puyodead1** [comment]
hmm, this is very odd. I'm not able to reproduce it on my end, but it looks like BuildTools is failing to download PortableGit (https://static.spigotmc.org/git/PortableGit-2.24.1.2-64-bit.7z.exe).

Do you have an active internet connection on the device you're attempting to use SSB on? Can you try manually downloading PortableGit from the link above, the exe is a self extracting ZIP file, the files should be extracted to a folder called ``PortableGit-2.24.1.2-64-bit`` inside the BuildTools directory like so:
![image](https://user-images.githubusercontent.com/14828766/90482001-a011eb80-e100-11ea-85f5-bf4985a5ecda.png)

**Comment by Swipperr** [comment]
I will try, and yes I do have a active connection

**Comment by Swipperr** [comment]
Same Thing, Am I just supposed to throw the git thing in there, or like?

**Comment by Swipperr** [comment]
uh, is the git supposed to have almost all of the same files the buildtools folder does? gimme a sec and i will whip up a video

**Comment by Swipperr** [comment]
[bandicam 2020-08-18 03-25-40-897.zip](https://github.com/Puyodead1-Development/SpigotServerBuilder/files/5088856/bandicam.2020-08-18.03-25-40-897.zip)

**Comment by Swipperr** [comment]
do u have any type of repository that I can access, and I accidentally misclicked "fork" i didnt want to fork nor meant to, how do i get rid rid of the fork?

**Comment by Puyodead1** [comment]
Haven’t had a chance to look at the video yet, but you can delete the fork in the settings menu at the bottom. I’ll look at the video later today. What do you mean by a repository you can access?

**Comment by Swipperr** [comment]
If u are okay with it can we please bring this to discord?

**Comment by Puyodead1** [comment]
> If u are okay with it can we please bring this to discord?

Sure, that’s actually easier for me

**Comment by Swipperr** [comment]
k my tag is Rythm#4360
